#!/usr/bin/env node

const AddressHandler = require('./index');

const ah = new AddressHandler({token: 'AIzaSyDaPAYeVqse7CfR6euboHdJbPWwMIn3uTU'});

const address = '8, boulevard de la bastille';

const addressObject = {
  street_number: '8',
  postal_code: '75012',
  route: 'Boulevard de la Bastille'
}

ah
.fromAddress(ah.toAddressString(addressObject))
.toAddressObject()
.then((data) => {
  console.log(data);
})
.catch((error) => {
  console.log(error);
});
