#!/usr/bin/env node

const AddressHandler = require('../index');

const myAddressHandler = new AddressHandler({ token: 'GOOGLE_TOKEN' });

console.log('Stringify an address object:\n');

console.log(myAddressHandler.toAddressString({
  street_number: '78',
  postal_code: '75015',
  route: 'Rue Olivier de Serres'
}));

myAddressHandler
.fromAddress('34 Avenue des Champs-Élysées, Paris')
.toAddressObject()
.then((data) => {
  console.log('\nGet an formatted object from address string :\n');
  console.log(data);
});

myAddressHandler
.fromPlaceId('ChIJVyt59Ptx5kcRS23JkTij3eo')
.toAddressObject()
.then((data) => {
  console.log('\nGet an formatted object from Google placeid :\n');
  console.log(data);
});
